apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi # The subject does not specify any amount
  accessModes:
    - ReadWriteOnce # Also totally arbitrary
  hostPath:
    path: "/var/lib/postgresql/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
