apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
#type: kubernetes.io/basic-auth
#data: 
#  username: postgres_user encoded base64
#  password: postgres_password encoded base64
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNfcGFzc3dvcmQNCg==
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
